apiVersion: v1
kind: Service
metadata:
  name: {{ include "company-registry.mongodb.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "company-registry.mongodb.name" . }}
    {{- include "company-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP       # not reachable from outside the cluster
  clusterIP: None       # headless — required by StatefulSet for pod identity
  publishNotReadyAddresses: true   # always resolve DNS even while pod is initializing
  selector:
    app: {{ include "company-registry.mongodb.name" . }}
  ports:
    - name: mongodb
      port: {{ .Values.mongodb.port }}
      targetPort: {{ .Values.mongodb.port }}
