apiVersion: v1
kind: Service
metadata:
  name: {{ include "company-registry.api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "company-registry.api.name" . }}
    {{- include "company-registry.labels" . | nindent 4 }}
spec:
  type: ClusterIP       # not reachable from outside the cluster
  selector:
    app: {{ include "company-registry.api.name" . }}
  ports:
    - name: http
      port: {{ .Values.api.port }}
      targetPort: {{ .Values.api.port }}
